using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace LeeTeke.HttpServerLite.AOT
{
    [Generator()]
    internal class RouterIncrementalGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var compilation = context.CompilationProvider;
            context.RegisterSourceOutput(compilation, (sourceProductionContext, c) =>
            {

                var codeCube = GetCoreCodeSource(c);
                // Build up the source code
                string source =
                    $$"""
                    // <auto-generated/>
                    using LeeTeke.HttpServerLite;
                    using System.Net;
                    using System;
                    using Microsoft.Extensions.DependencyInjection;

                    namespace LeeTeke.HttpServerLite.AOT
                    {     
                        public static class HttpServerLiteAOT
                        {
                        
                            public static HttpRouterAOT Router { get; } = new HttpRouterAOT();
        
                            public static void UseRouterAOT(this HttpListenerBuilder builder, IServiceProvider services)
                            {

                              {{codeCube}}

                            }
                        }
                    }
                """;
                sourceProductionContext.AddSource($"RouterIncrementalGenerator.g.cs", source);

            });
        }


        private string GetCoreCodeSource(Compilation compilation)
        {
            StringBuilder sb = new StringBuilder();
            var types = GetAllClasses(compilation.Assembly.GlobalNamespace).Where(p => p.BaseType?.ToString() == "LeeTeke.HttpServerLite.HttpControllerBase" || p.BaseType?.ToString() == "LeeTeke.HttpServerLite.VueHistoryModeRouter");
         
            int tag = 0;
            foreach (var type in types)
            {



                var routerName = $"router_{tag}";
                sb.AppendLine($"var {routerName} = services.GetRequiredService<{type}>();");
                sb.AppendLine($"Router.ControllerAdd({routerName}, builder);");
                sb.AppendLine($"var {routerName}_prefix = {routerName}.RoutePrefix == \"/\" ? {routerName}.RoutePrefix : $\"/{{{routerName}.RoutePrefix}}\";");

                if (type.BaseType?.Name == "VueHistoryModeRouter")
                {
                    //追加默认公式
                    sb.AppendLine($$"""
                             Router.TakeOverAdd({{routerName}}_prefix, (context) =>
                             {
                                 {{routerName}}.BeforeRoute(context, args =>
                                 {
                                      {{routerName}}.Index(context);
                                 });
                             });

                             Router.TakeOverAdd({{routerName}}_prefix+"assets/", (context) =>
                             {
                                 {{routerName}}.BeforeRoute(context, args =>
                                 {
                                      {{routerName}}.Index(context);
                                 });
                             });

                             """);
                }

                //获取所有的公共方法
                var members = type.GetMembers();
                foreach (IMethodSymbol member in members.OfType<IMethodSymbol>())
                {
                    if (member.Kind == SymbolKind.Method)
                    {


                        var atts = member.GetAttributes();
                        foreach (var att in atts)
                        {

                            if (att.AttributeClass?.ToString() == "LeeTeke.HttpServerLite.RouteAttribute")
                            {
                                var isTaskMember = member.ReturnType.Name == nameof(Task);

                                //ConstructorArguments 有且只有一个 string or string[]
                                if (att.ConstructorArguments[0].Kind == TypedConstantKind.Array)
                                {

                                    //多路由
                                    var routePaths = att.ConstructorArguments[0].Values.Select(p => $"{p.Value}");

                                    foreach (var item in routePaths)
                                    {
                                        var routePath = $"{item.Trim('/')}";

                                        if (member.Parameters.Length == 0 || (member.Parameters.Length > 0 && member.Parameters[0].Type.ToString() == "System.Net.HttpListenerContext"))
                                        {
                                            sb.AppendLine(RoterMethod(isTaskMember, routerName, routePath, member, false));
                                        }
                                    }

                                }
                                else if (att.ConstructorArguments[0].Value is string routePath)
                                {
                                    bool isTakeOver = false;
                                    routePath = $"{routePath.Trim('/')}";
                                    //继承但路由
                                    if (att.NamedArguments.Length > 0 && att.NamedArguments[0].Value.Value is bool takeover && takeover == true)
                                    {
                                        routePath += "/";
                                        isTakeOver = true ;
                                    }

                                    if (member.Parameters.Length == 0 || (member.Parameters.Length > 0 && member.Parameters[0].Type.ToString() == "System.Net.HttpListenerContext"))
                                    {
                                        sb.AppendLine(RoterMethod(isTaskMember, routerName, routePath, member, isTakeOver));
                                    }

                                }

                            }

                        }
                    }
                }


                sb.AppendLine();
                tag++;

            }

            return sb.ToString();
        }


        private static IEnumerable<INamedTypeSymbol> GetAllClasses(IAssemblySymbol assembly)
        {
            return GetAllClasses(assembly.GlobalNamespace);
        }

        private static IEnumerable<INamedTypeSymbol> GetAllClasses(INamespaceSymbol namespaceSymbol)
        {
            // 获取当前命名空间中的所有类型
            foreach (var type in namespaceSymbol.GetTypeMembers())
            {
                // 如果是类，则返回
                if (type.TypeKind == TypeKind.Class)
                {
                    yield return type;
                }
            }

            // 递归获取子命名空间中的类
            foreach (var subNamespace in namespaceSymbol.GetNamespaceMembers())
            {
                foreach (var classSymbol in GetAllClasses(subNamespace))
                {
                    yield return classSymbol;
                }
            }
        }


        private string RoterMethod(bool isTaskMember, string routerName, string routePath, IMethodSymbol member, bool isTakOver)
        {

            return $$"""
                Router.{{(isTakOver ? "TakeOverAdd" : "MainAdd")}}({{routerName}}_prefix + "{{routePath}}", (context) =>
                {
                    {{routerName}}.BeforeRoute(context, args =>
                    {
                        {{MoreParams(isTaskMember, routerName, member)}}
                    });
                });
                """;
        }

        private string TaskMethod(bool isTask, string content, string routerName)
        {
            if (isTask)
            {

                return $$"""
                    {{content.TrimEnd(';')}}.ContinueWith(t =>
                        {
                            if (t.IsFaulted)
                            {
                                {{routerName}}.RaiseException(context, t.Exception);
                            }
                        }, TaskContinuationOptions.OnlyOnFaulted).ConfigureAwait(false);
                    """;
            }
            else
            {
                return content;
            }

        }

        private string MoreParams(bool isTaskMember, string routerName, IMethodSymbol member)
        {
            if (member.Parameters.Length < 1)
            {
                return $$"""
                       {{TaskMethod(isTaskMember, $$"""
                       context.Close(HttpStatusCode.OK);                      
                       {{routerName}}.{{member.Name}}();
                       """, routerName)}}
                       """;
            }

            if (member.Parameters.Length == 1)
            {
                return $$"""{{TaskMethod(isTaskMember, $$"""{{routerName}}.{{member.Name}}(context);""", routerName)}}""";
            }


            var leftParameters = member.Parameters.Skip(1).Select(p => p.Type.ToString()).ToArray();

            string[] checkStr = new string[leftParameters.Length];
            string[] argsStr = new string[leftParameters.Length];

            for (int i = 0; i < leftParameters.Length; i++)
            {
                if (leftParameters[i].EndsWith("?"))
                {
                    argsStr[i] = $"args?[{i}] as {leftParameters[i]}";
                }
                else
                {
                    checkStr[i] = $"args?[{i}] is {leftParameters[i]} args_{i}";
                    argsStr[i] = $"args_{i}";
                }
            }

            var checkArgs = string.Join(", ", checkStr);
            if (checkArgs.Length < 1)
            {
                return $$"""{{TaskMethod(isTaskMember, $"{routerName}.{member.Name}(context, {string.Join(", ", argsStr)});", routerName)}}""";
            }
            else
            {
                return $$"""
                    if({{string.Join(", ", checkStr)}})
                    { 
                     {{TaskMethod(isTaskMember, $"{routerName}.{member.Name}(context, {string.Join(", ", argsStr)});", routerName)}}
                    }              
                    """;
            }
        }
    }
}
